# Generated by Django 5.0.6 on 2024-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('tipoMarca', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
            ],
        ),
    ]
