# Generated by Django 5.0.6 on 2024-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
